name: reconnect_yaml
main: net.md_5.bungee.module.reconnect.yaml.PluginYaml
version: git:reconnect_yaml:1.11-SNAPSHOT:a3fd2e9:unknown
description: Provides reconnect location functionality in locations.yml
author: SpigotMC
